-- CREAR TABLA AGRADECIMIENTOS
CREATE TABLE AGRADECIMIENTOS (
    IDAgradecimiento SMALLINT AUTO_INCREMENT,
    mensaje MEDIUMTEXT NOT NULL,
    IDEmisor CHAR(2) NOT NULL,
    IDReceptor CHAR(2) NOT NULL,
    -- PK
    CONSTRAINT PK_AGRADECIMIENTOS PRIMARY KEY (IDAgradecimiento),
    -- FK
    CONSTRAINT FK_AGRADECIMIENTOS_EMISOR FOREIGN KEY (IDEmisor) REFERENCES ALUMNOS(IDAlumno) ON DELETE CASCADE,
    CONSTRAINT FK_AGRADECIMIENTOS_RECEPTOR FOREIGN KEY (IDReceptor) REFERENCES ALUMNOS(IDAlumno) ON DELETE CASCADE
);