INSERT INTO alumnos (idAlumno, clave, nombre, webAlumno, jesuita, imagen, informacion) VALUES
('01', 'clave01', 'Manuel Amigo Royan', 'manuel_amigo', 'Ignacio de Loyola', 'img/ignacio.jpg', 'Fundador de la Compañía de Jesús'),
('02', 'clave02', 'Samuel Barril Sosa', 'samuel_barril', 'Francisco Javier', 'img/javier.jpg', 'Misionero clave en Asia'),
('03', 'clave03', 'Yehu Blanco Pinilla', 'yehu_blanco', 'Pedro Arrupe', 'img/arrupe.jpg', 'Renovador de la orden en el siglo XX'),
('04', 'clave04', 'Jose Antonio Bodes Garcia', 'jose_bodes', 'Matteo Ricci', 'img/ricci.jpg', 'Introdujo el cristianismo en China'),
('05', 'clave05', 'Carlos Colorado Anselmo', 'carlos_colorado', 'José de Anchieta', 'img/anchieta.jpg', 'Misionero en Brasil y lingüista'),
('06', 'clave06', 'Francisco Javier Corchado Parejo', 'francisco_corchado', 'Roberto Belarmino', 'img/belarmino.jpg', 'Teólogo clave de la Contrarreforma'),
('07', 'clave07', 'Javier Cumplido Barahona', 'javier_cumplido', 'Alberto Hurtado', 'img/hurtado.jpg', 'Defensor de los pobres en Chile'),
('08', 'clave08', 'Diego Evaristo Santiago', 'diego_evaristo', 'Pedro Claver', 'img/claver.jpg', 'Protector de los esclavos en América'),
('09', 'clave09', 'Sergio Fuente Fuentes', 'sergio_fuente', 'Baltasar Gracián', 'img/gracian.jpg', 'Escritor del Siglo de Oro'),
('10', 'clave10', 'Javier Garcia Silverio', 'javier_garcia', 'Juan de Mariana', 'img/mariana.jpg', 'Pensador político y economista'),
('11', 'clave11', 'Abraham García Nevado', 'abraham_garcia', 'José María Rubio', 'img/rubio.jpg', 'Jesuita español canonizado'),
('12', 'clave12', 'Angelo Gianpierre Gomez Cardoza', 'angelo_gomez', 'Teilhard de Chardin', 'img/teilhard.jpg', 'Científico y teólogo evolucionista'),
('13', 'clave13', 'Nicolas Manuel Gonzalez Morera', 'nicolas_gonzalez', 'Antonio Ruiz de Montoya', 'img/montoya.jpg', 'Misionero en Paraguay'),
('14', 'clave14', 'Aitor Gragera Martin', 'aitor_gragera', 'Juan Roothaan', 'img/roothaan.jpg', 'Restaurador de la Compañía en el siglo XIX'),
('15', 'clave15', 'Hugo Hernandez Royano', 'hugo_hernandez', 'Adolfo Nicolás', 'img/nicolas.jpg', 'Superior General reciente'),
('16', 'clave16', 'Teresa Hernandez Sanchez', 'teresa_hernandez', 'Karl Rahner', 'img/rahner.jpg', 'Influyente teólogo del siglo XX'),
('17', 'clave17', 'Francisco Hurtado Guijarro', 'francisco_hurtado', 'Luis de Molina', 'img/molina.jpg', 'Teórico de la libertad humana'),
('18', 'clave18', 'Francisco Javier Medina Gordillo', 'francisco_medina', 'José Sánchez del Río', 'img/sanchez.jpg', 'Joven mártir mexicano'),
('19', 'clave19', 'Sergio Poves Camisón', 'sergio_poves', 'Miguel Pro', 'img/pro.jpg', 'Mártir durante la persecución en México'),
('20', 'clave20', 'Sara Rivero Caminero', 'sara_rivero', 'Fernando Hoyos', 'img/hoyos.jpg', 'Jesuita comprometido con la justicia social'),
('21', 'clave21', 'Ivan Rodriguez Gomez-Landero', 'ivan_rodriguez', 'Ignacio Ellacuría', 'img/ellacuria.jpg', 'Asesinado por defender derechos humanos'),
('22', 'clave22', 'Daniel Vega Garcia', 'daniel_vega', 'Jon Sobrino', 'img/sobrino.jpg', 'Teólogo de la liberación'),
('23', 'clave23', 'Rubi Villalon Arranz', 'rubi_villalon', 'Vicente Cañas', 'img/canas.jpg', 'Misionero entre indígenas en Brasil'),
('24', 'clave24', 'Antonio Villareal Moreno', 'antonio_villareal', 'Cristóbal López Romero', 'img/lopez.jpg', 'Cardenal y arzobispo actual'),
('25','clave25','Lucas','Lucas_web','jesuita','img/lucas.jpg','frase25');

    